### ISSUE TITLE
`FromField` and others should return `Option`

### ISSUE THREAD

**Issue by Mingun** [TedDriggs/darling#167]
In #165 I faced with the problem, that darling returns me a default initialized object instead of an `Option` when the attribute is missed. That is not idiomatic. Trait `FromField` (and probably others) should be changed to return an `Option` where `None` indicated that requested attribute is missing. It is possible also return a special `Error` kind, but it seems non-ergonomic:

### Macro code
```rust
use darling::FromField;
use syn::{parse_macro_input, Data, DeriveInput, Fields};
use proc_macro::TokenStream;
use quote::ToTokens;

#[derive(Debug, Default, FromField)]
#[darling(default)]
#[darling(attributes(xml))]
struct FieldProps {
  /// Should be `true` when `#[xml(attribute)]` is present on a field and false otherwise:
  ///
  /// ```rust
  /// // ---> true
  /// #[xml(attribute)]
  /// field1: (),
  ///
  /// // ---> false
  /// #[xml]
  /// field2: (),
  ///
  /// // FieldProps is not available
  /// field3: (),
  /// ```
  attribute: bool,
  // other attributes...
}

#[proc_macro_attribute]
pub fn quick_xml(_attr: TokenStream, item: TokenStream) -> TokenStream {
  let ast = parse_macro_input!(item as DeriveInput);

  if let Data::Struct(s) = &ast.data {
    if let Fields::Named(fields) = &s.fields {
      for f in &fields.named {
        let props = FieldProps::from_field(&f);

        println!("{}: {:?}", f.ident.as_ref().unwrap().to_string(), props);
      }
    }
  }

  ast.into_token_stream().into()
}
```

### Test Input:
```rust
#[quick_xml]
struct {
  #[xml(attribute)]
  field1: (),
  field2: (),
}
```

### Expected output
```rust
field1: Ok(Some(FieldProps { attribute: true }))
field2: Ok(None)
```
or
```rust
field1: Ok(FieldProps { attribute: true })
field2: Err(...)
```
but variant with `Option` is better

### Actual output
```rust
field1: Ok(FieldProps { attribute: true })
field2: Ok(FieldProps { attribute: false })
```

**Comment by TedDriggs** [comment]
If `attribute` is required, then don't set `#[darling(default)]` on the struct deriving `FromField`. That way, failing to specify it it will produce an error.

---

In this example, what would you consider the correct interpretation of the following input?

```rust
#[quick_xml]
struct Example {
    #[xml]
    #[xml(attribute)]
    #[xml]
    field1: ()
}
```

**Comment by Mingun** [comment]
> Defaulting is the [first item in the features list](https://github.com/TedDriggs/darling#features), and there's [an integration test showing some of the more complex defaulting cases](https://github.com/TedDriggs/darling/blob/master/tests/defaults.rs).

The sentence:
> **Defaults**: Supports struct- and field-level defaults, using the same path syntax as `serde`.

still say nothing about where attribute can be used, only that you can use it in form `#[darling(default)]` or `#[darling(default = "path::to::function")]`

> `serde` has [45 contributors to its documentation site](https://github.com/serde-rs/serde-rs.github.io), and dtolnay - serde's maintainer - has [163 sponsors](https://github.com/sponsors/dtolnay) for his Rust work.

`serde` bugs does not fixed by years and dtolnay even does not consider that it can be fixed by anyone, so I don't understand what you trying to say by this sentence. I do not require you to create a site like serde have. Just add a few points to the rustdoc comments about using derives and attributes, supported by every derive. Everyone can do that but you, as an author, has a better knowledge how to write it in a good way, so it is not a crime to ask you to do that. In the end, this kind of work is what put in the word "maintenance". If you cannot, just leave issue opened so someone can see that problem exists and could make a PR for it.

Also, I don't understand, why you think that issue is resolved.


> In this case, `#[xml]` would be seen by `darling` but since they have no bodies they would have no effect. That would leave `#[xml(attribute)]`, which would cause this to be an attribute.

That all good, but how I should forbid using `#[xml]` when technically all macro properties are optional? All optional, but at least one should be present. How I should understand that my attribute even didn't exist? Even if `#[xml]` is acceptable it is impossible to figure out if attribute is present:

```rust
// quick_xml_macro crate
use darling::FromField;
use darling::ToTokens;
use syn::{parse_macro_input, Data, DeriveInput, Fields};
use proc_macro::TokenStream;

/// This will parsed successfully if no `#[xml(...)]` are present or
/// `#[xml]` without parameters is present
#[derive(Debug, FromField)]
#[darling(attributes(xml))]
struct AbsentOrEmptyXml;

#[proc_macro_attribute]
pub fn xml(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let ast = parse_macro_input!(item as DeriveInput);

    if let Data::Struct(s) = &ast.data {
        if let Fields::Named(fields) = &s.fields {
          for f in &fields.named {
            let props = AbsentOrEmptyXml::from_field(&f);

            println!("{}:", f.ident.as_ref().unwrap());
            println!("- {:?}", props);
          }
        }
    }

    ast.into_token_stream().into()
}
Input:
```rust
#[quick_xml_macro::xml]
struct Xml {
    no: (),

    #[xml]
    wrong: (),

    #[xml(attribute)]
    correct: (),

    #[xml(attribute)]
    #[xml(content)]
    multiple1: (),

    #[xml(attribute, content)]
    multiple2: (),

    #[xml(attribute)]
    #[xml]
    multiple_wrong: (),
}
```
Output:
```yaml
no:
- Ok(AbsentOrEmptyXml)
wrong:
- Ok(AbsentOrEmptyXml)
correct:
- Err(Error { kind: UnknownField(ErrorUnknownField { name: "attribute", did_you_mean: None }), locations: [], span: Some(#0 bytes(87..96)) })
multiple1:
- Err(Error { kind: Multiple([Error { kind: UnknownField(ErrorUnknownField { name: "attribute", did_you_mean: None }), locations: [], span: Some(#0 bytes(127..136)) }, Error { kind: UnknownField(ErrorUnknownField { name: "content", did_you_mean: None }), locations: [], span: Some(#0 bytes(149..156)) }]), locations: [], span: None })
multiple2:
- Err(Error { kind: Multiple([Error { kind: UnknownField(ErrorUnknownField { name: "attribute", did_you_mean: None }), locations: [], span: Some(#0 bytes(189..198)) }, Error { kind: UnknownField(ErrorUnknownField { name: "content", did_you_mean: None }), locations: [], span: Some(#0 bytes(200..207)) }]), locations: [], span: None })
multiple_wrong:
- Err(Error { kind: UnknownField(ErrorUnknownField { name: "attribute", did_you_mean: None }), locations: [], span: Some(#0 bytes(240..249)) })
```

How to distinguish between `no` and `wrong` cases? They returns identical results! As you see, now nothing `default`s specified
