### ISSUE TITLE
Add rustfmt to the project and travis

### ISSUE THREAD

**Issue by Luro02** [TedDriggs/darling#88]
`rustfmt` is a tool, that formats rust code.
https://github.com/rust-lang/rustfmt

It is in most projects, to keep the codebase clean and I would recommend using it and letting the CI fail, if the code has not been formatted with rustfmt.
https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server

The tool can be customized with a `rustfmt.toml` in the crate root (the same folder, that `Cargo.toml` is in), I recommend the following configurations
```toml
error_on_unformatted = true
edition = "2018"
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
match_arm_blocks = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
```
